#!/usr/bin/env python3
"""Import and validate the official Gomocup expert-selected opening files."""

from __future__ import annotations

import argparse
import hashlib
import json
import zipfile
from pathlib import Path


MEMBERS = {
    "freestyle15": "openings/openings_freestyle15.txt",
    "standard": "openings/openings_standard.txt",
    "renju": "openings/openings_renju.txt",
    "caro": "openings/openings_caro.txt",
    "freestyle20": "openings/openings_freestyle20.txt",
}


def transform(point: tuple[int, int], variant: int, size: int = 15) -> tuple[int, int]:
    x, y = point
    n = size - 1
    return (
        (x, y), (y, n - x), (n - x, n - y), (n - y, x),
        (n - x, y), (x, n - y), (y, x), (n - y, n - x),
    )[variant & 7]


def has_five(board: list[list[int]], x: int, y: int, side: int) -> bool:
    for dx, dy in ((1, 0), (0, 1), (1, 1), (1, -1)):
        total = 1
        for sign in (-1, 1):
            px, py = x + sign * dx, y + sign * dy
            while 0 <= px < 15 and 0 <= py < 15 and board[px][py] == side:
                total += 1
                px += sign * dx
                py += sign * dy
        if total >= 5:
            return True
    return False


def parse_lines(text: str) -> list[list[tuple[int, int]]]:
    lines: list[list[tuple[int, int]]] = []
    for number, raw in enumerate(text.splitlines(), 1):
        raw = raw.strip()
        if not raw:
            continue
        values = [int(value.strip()) for value in raw.split(",")]
        if len(values) % 2:
            raise ValueError(f"line {number}: odd coordinate count")
        moves = list(zip(values[0::2], values[1::2]))
        if not moves or len(moves) > 25:
            raise ValueError(f"line {number}: unsupported length")
        lines.append(moves)
    return lines


def validate_freestyle(moves: list[tuple[int, int]], index: int) -> None:
    board = [[0] * 15 for _ in range(15)]
    for ply, (rx, ry) in enumerate(moves):
        x, y = 7 + rx, 7 + ry
        if not (0 <= x < 15 and 0 <= y < 15):
            raise ValueError(f"opening {index}, ply {ply}: outside 15x15")
        if board[x][y] != 0:
            raise ValueError(f"opening {index}, ply {ply}: duplicate point")
        side = 1 if ply % 2 == 0 else -1
        board[x][y] = side
        if has_five(board, x, y, side) and ply + 1 != len(moves):
            raise ValueError(f"opening {index}, ply {ply}: terminal prefix")


def canonical(moves: list[tuple[int, int]]) -> tuple[list[tuple[int, int]], int]:
    absolute = [(7 + x, 7 + y) for x, y in moves]
    variants: list[tuple[tuple[tuple[int, int], ...], int]] = []
    for variant in range(8):
        normalized = tuple((x - 7, y - 7) for x, y in
                           (transform(point, variant) for point in absolute))
        variants.append((normalized, variant))
    best, variant = min(variants)
    return list(best), variant


def compact_moves(moves: list[tuple[int, int]]) -> str:
    return " ".join(f"{x},{y}" for x, y in moves)


def write_asset(path: Path, lines: list[list[tuple[int, int]]], source_hashes: list[str]) -> None:
    rendered = [
        "/* Generated by tools/import_gomocup_openings.py from the official",
        " * Gomocup 2024-2025 expert-selected Freestyle-15 opening sets.",
        f" * Source archive SHA-256 values: {', '.join(source_hashes)}. */",
        "typedef struct {",
        "    unsigned char length;",
        "    signed char coordinates[50];",
        "} FCOpeningLine;",
        "",
        "static const FCOpeningLine fcOpeningLines[] = {",
    ]
    for moves in lines:
        values = ", ".join(f"{value:2d}" for point in moves for value in point)
        rendered.append(f"    {{{len(moves)}, {{{values}}}}},")
    rendered.extend([
        "};", "", "static const int fcOpeningLineCount =",
        "    (int)(sizeof(fcOpeningLines) / sizeof(fcOpeningLines[0]));", "",
    ])
    path.write_text("\n".join(rendered), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--package", required=True, action="append", type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--asset", required=True, type=Path)
    args = parser.parse_args()

    partitions: dict[str, dict[str, object]] = {}
    source_packages: list[dict[str, object]] = []
    selected_member = MEMBERS["freestyle15"]
    records: list[tuple[int, int, list[tuple[int, int]], bytes]] = []
    source_hashes: list[str] = []
    for package in args.package:
        package_bytes = package.read_bytes()
        package_hash = hashlib.sha256(package_bytes).hexdigest()
        source_hashes.append(package_hash)
        year = 2024 if "2024" in package.name else 2025
        with zipfile.ZipFile(package) as archive:
            available = set(archive.namelist())
            year_partitions: dict[str, object] = {}
            for rule, member in MEMBERS.items():
                if member not in available:
                    year_partitions[rule] = {"member": member, "present": False}
                    continue
                payload = archive.read(member)
                parsed = parse_lines(payload.decode("utf-8-sig"))
                year_partitions[rule] = {
                    "member": member, "present": True,
                    "openingCount": len(parsed),
                    "memberSha256": hashlib.sha256(payload).hexdigest(),
                }
            selected_payload = archive.read(selected_member)
            selected_lines = parse_lines(selected_payload.decode("utf-8-sig"))
            for index, moves in enumerate(selected_lines):
                records.append((year, index, moves, selected_payload))
        partitions[str(year)] = year_partitions
        source_packages.append({
            "year": year,
            "resultsUrl": f"https://gomocup.org/results/gomocup-result-{year}",
            "packageUrl": f"https://gomocup.org/static/tournaments/{year}/results/gomocup{year}results.zip",
            "packageSha256": package_hash,
        })

    seen: dict[str, int] = {}
    entries: list[dict[str, object]] = []
    duplicates: list[dict[str, int]] = []
    for runtime_index, (year, index, moves, selected_payload) in enumerate(records):
        validate_freestyle(moves, index)
        canonical_moves, canonical_transform = canonical(moves)
        identity = hashlib.sha256(compact_moves(canonical_moves).encode()).hexdigest()[:16]
        if identity in seen:
            duplicates.append({"openingIndex": runtime_index,
                               "duplicateOf": seen[identity]})
        else:
            seen[identity] = runtime_index
        entries.append({
            "openingIndex": runtime_index,
            "originalIdentifier": f"gomocup-{year}/openings_freestyle15.txt:{index + 1}",
            "rule": "Freestyle-15", "boardSize": 15,
            "moveCount": len(moves), "movesRelative": moves,
            "canonicalMovesRelative": canonical_moves,
            "canonicalTransform": canonical_transform,
            "canonicalId": identity,
            "sourceOrganization": "Gomocup",
            "event": f"Gomocup {year}", "year": year,
            "sourceUrl": f"https://gomocup.org/results/gomocup-result-{year}",
            "packageUrl": f"https://gomocup.org/static/tournaments/{year}/results/gomocup{year}results.zip",
            "sourceMemberSha256": hashlib.sha256(selected_payload).hexdigest(),
            "redistributionStatus": "Attributed coordinate extraction; source archive not bundled",
        })

    near_duplicates: list[dict[str, int]] = []
    for left in range(len(entries)):
        a = entries[left]["canonicalMovesRelative"]
        for right in range(left + 1, len(entries)):
            b = entries[right]["canonicalMovesRelative"]
            common = 0
            for first, second in zip(a, b):
                if first != second:
                    break
                common += 1
            if common >= 3:
                near_duplicates.append({"left": left, "right": right,
                                        "commonPrefixPlies": common})

    manifest = {
        "schemaVersion": 2,
        "libraryVersion": "gomocup-2024-2025-freestyle15-v2",
        "sourcePackages": source_packages,
        "sourceMember": selected_member,
        "retrievedAt": "2026-08-13",
        "selectionPolicy": "All official expert-selected Freestyle-15 lines from Gomocup 2024 and 2025; no outcome weights or training data.",
        "rulePartitions": partitions,
        "entries": entries,
        "exactDuplicates": duplicates,
        "nearDuplicates": near_duplicates,
        "excludedResearchSources": [{
            "organization": "Renju International Federation / RenjuNet",
            "url": "https://www.renju.net/",
            "reason": "Research only: visible All rights reserved notice; no records bundled.",
        }],
    }
    args.manifest.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
                             encoding="utf-8")
    write_asset(args.asset, [record[2] for record in records], source_hashes)
    print(f"validated {len(records)} Freestyle-15 openings; duplicates={len(duplicates)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
